language: cpp

# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code e.g. by calling make
script:
  - cd doc && doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    
before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search
